### ISSUE TITLE
zap2epg doesn't run when trying to retrieve OTA data.

### ISSUE THREAD

**Issue by chrisyroid** [edit4ever/script.module.zap2epg#1]
Hi. I installed this on Kodi and receive these errors when trying to run zap2epg.

```
2017/12/12 10:38:08 Kodi settings version is: None
2017/12/12 10:38:08 Running zap2epg-0.6.1 for zipcode: 87110 and lineup: Local Over the Air Broadcast
2017/12/12 10:38:08 Accessing Tvheadend channel list from: http://127.0.0.1:9981
2017/12/12 10:38:08 Exception: main
Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.zap2epg/zap2epg.py", line 701, in mainRun
    tvhMatchGet()
  File "/storage/.kodi/addons/script.module.zap2epg/zap2epg.py", line 115, in tvhMatchGet
    channels = json.load(response)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 0: unexpected end of data
```

**Comment by edit4ever** [comment]
Looks like an issue with the TVehadend channel match function.  It likely means that there is an invalid charcter being used in the channel name transmitted by the station.  Try turning off the "Append Tvheadend Service Name" option in the settings and rerun.  If that works - I'd like to get a copy of your tvheadend serviec list so I can see what the invalid character is.

**Comment by edit4ever** [comment]
Enter the following into a web browser and then save the response to a text file and upload it here.

http://YOUR.IP.ADDRESS:9981/api/mpegts/service/grid

replace YOUR.IP.ADDRESS with the ip address of your tvheadend server.

**Comment by chrisyroid** [comment]
Okay. Here you go:
https://pastebin.com/xwXm2iyw

I'm going to be gone for a while. BTW Kodi is taking a long time to download the EPG.

**Comment by edit4ever** [comment]
Yeah - if you have it set for full extra options and a full 14 days of data - the first run will take awhile.

If you want to stop it (just restart kodi) and try this test version it should only try to match enabled channels - which should solve your issue:

[script.module.zap2epg-0.6.2-TEST.zip](https://github.com/edit4ever/script.module.zap2epg/files/1552938/script.module.zap2epg-0.6.2-TEST.zip)

**Comment by chrisyroid** [comment]
Awesome! I got it working!

**Comment by edit4ever** [comment]
Glad to hear it! Can you confirm that the "Append Tvheadend Service Name" works for you with the TEST version?

**Comment by chrisyroid** [comment]
The test version works. Although the EPG wouldn't update until I re-ran the grabber within the Tvheadend GUI.
