### ISSUE TITLE
Feature Request: Add option to remove prohibited characters from series title

### ISSUE THREAD

**Issue by RKCRLR** [edit4ever/script.module.zap2epg#13]
Tvheadend has an option to use Windows safe filenames when recordings are made however this does not extend to the sub-directories that are created for scheduled recordings.  This causes Autorecs to fail when a prohibited character is in the series title (i.e., the ":" in "NCIS: New Orleans" or "NCIS: Los Angeles").  
The workaround is to manually remove the prohibited character in folder to be created when creating the timer or in the Autorecs tab.  
Tvheadend is planning to address this in version 4.4 but it would be nice to have an option to remove prohibited characters from the series title in the mean time.

**Comment by edit4ever** [comment]
I took a look at the tvheadend code and it should be an easy fix for them to add it.  Since I don't expect it will take that long - I don't want to permanently add this feature to zap2epg.  However, to get you through for now - I created a version of zap2epg with the feature added that you can use.

Here you go:
https://www.dropbox.com/s/z689mmjn28lg0uo/script.module.zap2epg-1.2.0-safetitle.zip?dl=0

**Comment by RKCRLR** [comment]
Thanks!  I’ll give this a try and see how it works.  

Sent from Mail for Windows 10

**Comment by RKCRLR** [comment]
Any possibility you can add this option in version 2.X?
I'm contemplating going to Kodi 19 and this option would be nice to
retain.
I submitted a bug report to Tvheadend and they said they were going to fix
it in version 4.4.  However I got a notice the other day that it has now
been postponed until version 4.6.

**Comment by edit4ever** [comment]
Give this version a try and see if it works for you - only good on Kodi 19.
https://www.dropbox.com/s/ra21ufezsevuwnu/script.module.zap2epg-2.0.0-safetitle.zip?dl=0

**Comment by RKCRLR** [comment]
Thanks, I’ve installed it.  I’ll wait for the next guide update to see if it works.  

Sent from Mail for Windows 10

**Comment by RKCRLR** [comment]
I tried manually updating the guide data and am getting an error.  I reinstalled version 2.0.0 and still get the error.  I also get an error when I open Configure Channel List when I exit even if I just back out.  
Strange thing is that safetitle appeared to run OK last night when scheduled.  
I’ve attached my Kodi logfile and the zap2epg logfile.

Sent from Mail for Windows 10

From: Sterling
Sent: Wednesday, February 24, 2021 12:40 PM
To: edit4ever/script.module.zap2epg; edit4ever/script.module.zap2epg
Cc: Author
Subject: RE: [edit4ever/script.module.zap2epg] Feature Request: Add optiontoremove prohibited characters from series title (#13)

Thanks, I’ve installed it.  I’ll wait for the next guide update to see if it works.  

Sent from Mail for Windows 10

**Comment by edit4ever** [comment]
no attachments. :-(

**Comment by RKCRLR** [comment]
I don’t know what it is about Outlook Mail that makes it sometimes strip off attachments.  

I’ll try again from Outlook 2007.  

Let me know if this doesn’t work.

**Comment by edit4ever** [comment]
Nope – try sending from your normal email directly to my gmail account.


Jay Maloney

**Comment by RKCRLR** [comment]
Is your gmail jay.maloney@gmail.com?

**Comment by edit4ever** [comment]
edit4ever@gmail.com
