### ISSUE TITLE
Movie year to subtitle

### ISSUE THREAD

**Issue by mathieugouin** [edit4ever/script.module.zap2epg#18]
Hello, 

The original zap2xml.pl script supported an option (-M):
`-M = copy movie_year to empty movie sub-title tags`

Is the option still available?

**Comment by edit4ever** [comment]
zap2epg doesn't have that option.  Instead it has the option to add whatever content details you want to the the details string.  You can build that layout order anyway you like - which is helpful as different kodi skins handle the epg display differently.

**Comment by mathieugouin** [comment]
Can you confirm if to enable the details string it forces to download an additional request per program?

**Comment by edit4ever** [comment]
Yes - as that is the way the information is stored on the server - full episode info can only be requested with an additional post request - basic episode info is available without it.

**Comment by mathieugouin** [comment]
That is strange, I was able to get the following.  See `            "releaseYear": "1971", `

```json
    {
      "callSign": "WCAXDT2",
      "affiliateCallSign": "null",
      "channelId": "53498",
      "channelNo": "3.2",
      "events": [
        {
          "callSign": "WCAXDT2",
          "duration": "140",
          "startTime": "2020-01-21T01:00:00Z",
          "endTime": "2020-01-21T03:20:00Z",
          "thumbnail": "p38974_p_v8_aa",
          "channelNo": "3.2",
          "filter": [
            "filter-movie"
          ],
          "seriesId": "MV00006109",
          "rating": "TV-14",
          "flag": [],
          "tags": [],
          "program": {
            "title": "Something Big",
            "id": "MV000061090000",
            "tmsId": "MV000061090000",
            "shortDesc": "An outlaw (Dean Martin) plans to swap a cavalry colonel's (Brian Keith) wife (Honor Blackman) for a Gatling gun needed to rob a Mexican bandit.",
            "season": null,
            "releaseYear": "1971",
            "episode": null,
            "episodeTitle": null,
            "seriesId": "MV00006109",
            "isGeneric": "0"
          }
        },

```

**Comment by mathieugouin** [comment]
Also, I have in my settings:

```xml
    <setting id="xdetails" default="true">false</setting>
```

**Comment by edit4ever** [comment]
Go ahead and set this to true and pull one day of info. Then you will see the extra data that is downloaded for each episode. I'm guessing you are not using the Kodi interface?

**Comment by mathieugouin** [comment]
Yes, both interfaces.  But for debugging at my PC, I prefer direct editing of files ;)

It's ok... I was just hoping to get the info I like without having the big download overhead of extra data.  I'm downloading 14 days of data...
