### ISSUE TITLE
What is the definition for epgenre (0, 1, 2)?

### ISSUE THREAD

**Issue by mathieugouin** [edit4ever/script.module.zap2epg#19]
I looked a bit at your code and it seems related to the way how the genre are parsed.  But I don't get the whole picture.  Could you explain a bit?  
0 = ?
1 = ?
2 = ?

Thanks!

**Comment by edit4ever** [comment]
Because of the limitation that tvheadend and kodi have in working with genres - this gives you the option to add some color to some of the epg skins in kodi.  It works by changing/adding a genre to the list that is supported by kodi/tvheadend - based on the standard they use.  You can see some of the original discussion here :  https://tvheadend.org/boards/12/topics/25524?r=30657#message-30657

I haven't gone back to see if either side has worked on updates for this.  Basically, the three settings give you the option to remap more or less of the genres for a simple color scheme - or none at all.  And the option to not change what tvheadend sets for kodi - which usually leaves a broken color scheme.

**Comment by mathieugouin** [comment]
Ok, thanks for the reply.  I can confirm that with default setting of "2", it does not populate the category/genre at all.  I have both canadian & US channels.  I have confirmed this by looking at the xmltv.xml output.

Normally, it outputs something like:
`<category lang="en">Children's / Youth programmes</category>`

Are you open to pull request?  I think I have a working solution.   At least for option 2.  I'm not fully sure what is the goal of the different mapping style.  Hence my original question.

**Comment by edit4ever** [comment]
Strange - does setting option 1 (Simple) work to generate the genres?

I assume you have Download Extra Details enabled - as that is the only way to get genre info.

And yes - I'm open to PR - I haven't worked on this in quite a bit - so open to updates/fixes.

**Comment by mathieugouin** [comment]
No, option 1 does not work either.  I looked at the code and with current implementation, none of them should work.

That is strange, as I was able with a simple code fix to have the genre without the extra details.

Have a look at the json in the cache.  The info is all there ;)  See this snippet of one of the json downloaded without the extra details.

```json
        {
          "callSign": "CBFTDT",
          "duration": "61",
          "startTime": "2020-01-22T22:59:00Z",
          "endTime": "2020-01-23T00:00:00Z",
          "thumbnail": "p14477611_b_v9_ab",
          "channelNo": "2.1",
          "filter": [
            "filter-news"
          ],
          "seriesId": "SH02763152",
          "rating": null,
          "flag": [
            "New"
          ],
          "tags": [
            "CC"
          ],
          "program": {
            "title": "Le téléjournal avec Patrice Roy",
            "id": "SH027631520000",
            "tmsId": "SH027631520000",
            "shortDesc": "Le magazine quotidien de l'information de la région de Montréal.",
            "season": null,
            "releaseYear": null,
            "episode": null,
            "episodeTitle": null,
            "seriesId": "SH02763152",
            "isGeneric": "0"
          }
        }
```

**Comment by edit4ever** [comment]
There is no genre information in that data set. That is basic details for an episode. To get genre I for you have to pull the data for the tmsId number.

**Comment by mathieugouin** [comment]
So you are saying that:

```json
          "filter": [
            "filter-news"
          ],
``` 

is not considered genre?  Ok, that got me confused... especially with the code that removes 'filter-' and translate it to tvheadend format...
