### ISSUE TITLE
missing guide info

### ISSUE THREAD

**Issue by howudodat** [edit4ever/script.module.zap2epg#21]
Dont know if I have this set up correctly or not.  It seems that tvh is still using ota data instead of data from zap2epg.  
1.  I only see 3 days of data (and partial at that) even though it's set for 7, it looks a lot like OTA data.
2.  There are certain channels that are completel missing.

What is the grabber config supposed to look like on tvh?  When I go to a channels and disable automatic mapping, EPG Source dropdown has no options in it's droplist.

**Comment by edit4ever** [comment]
To know if zap2epg is working - see if there is an xmtv.xml generated.  In TVH you have to enable the grabber then it's best to restart the system to trigger a new download of channels. (May takea  few minutes) after that - you need to assign the epg source in tvh for each channel.

The easiest way to get setup is to use the zap2epg wizard in Kodi - that's what it is designed for!

**Comment by howudodat** [comment]
which grabber do I need to enable in TVH?  I think that's the problem.  I ran the wizard and that went fine.  It said it downloaded some 70 channels and 3000+ episodes (dont remember the exact number).

**Comment by edit4ever** [comment]
perfect - that means it worked. You may need to restart the system to get Kodi to refresh the tv guide data.  In the TVH  webUI you should see the channels assigned to the zap2epg source for the epg grabber.

**Comment by howudodat** [comment]
I removed epgdb in tvh and rebooted seems like that did the trick.  Thanks for the quick response!  Now I'm gonna go and check out your tvh config add on...good work man!
