### ISSUE TITLE
Can't Connect To TVheadend

### ISSUE THREAD

**Issue by mattr254** [edit4ever/script.module.zap2epg#22]
Running script on linux mint w/Kodi 18.6 connected to TVheadend. The script can verify if the user/pass is correct incorrect, but when it tries to connect it states "Could not connect to Tvheadend Server, please check your Tvheadend Server is running (which it is) or check the port configuration in the settings( which is set to http 9981 by default) I'm at a loss what to do here

**Comment by edit4ever** [comment]
Can you provide the log for zap2epg?  I assume you can access the Tvheadend webui from a browser?

**Comment by edit4ever** [comment]
closing - due to lack of response.
