### ISSUE TITLE
Scrap fails with message "xmltv: /usr/bin/tv_grab_zap2epg: htsmsg_xml_deserialize error Unknown syntatic element:"

### ISSUE THREAD

**Issue by wbeard52** [edit4ever/script.module.zap2epg#24]
Apparently, this error occurred over the past week.  I can download all the data by looking at the cache folder but the scrap fails with this message.  

I am running OSMC Buster.  It is based on Debian buster and it could be the latest changes to the OS has caused this issue.  Any advice on troubleshooting would be appreciated.

Thanks

**Comment by edit4ever** [comment]
Is it possible for you to share your zap2epg log?

**Comment by wbeard52** [comment]
Absolutely.  Where is the log located?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by edit4ever** [comment]
Should be under your /userdata/script.module.zap2epg folder.

**Comment by wbeard52** [comment]
I don’t know if it will help you.  Show shows at the very end it had written the xmltv file.  I am using Kodi 18.8 with TVH version 4.2.8

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
In that case - I would like to get a copy of the xmltv file that was generated.

**Comment by wbeard52** [comment]
I attached the log file but apparently it didn't come through.  

[zap2epg.log](https://github.com/edit4ever/script.module.zap2epg/files/5447867/zap2epg.log)
[zap2epg.zip](https://github.com/edit4ever/script.module.zap2epg/files/5447869/zap2epg.zip)

**Comment by edit4ever** [comment]
Definitely a clean run – so please send the xmltv.xml file and I’ll have a look.

It’s usually an issue with a station including some kind of strange character that kodi doesn’t recognize.  This should be converted – but something may be up.


Jay M

**Comment by wbeard52** [comment]
The xml file is located inside the zip file.  Thank you for your help.  It is appreciated.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
Thanx – missed that…I’ll have a look.


Jay M

**Comment by edit4ever** [comment]
Was there any additional info in this kodi log line?
`xmltv: /usr/bin/tv_grab_zap2epg: htsmsg_xml_deserialize error Unknown syntatic element:`
Specifically it would be nice if it had a line number there.

**Comment by wbeard52** [comment]
No.  Unfortunately.  I was looking for a line number.  After that line, it simply stated it grabbed no data.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wbeard52** [comment]
I ran it again.
2020-10-27 13:28:03.467 xmltv: /usr/bin/tv_grab_zap2epg10: htsmsg_xml_deserialize error Unknown syntatic element:
2020-10-27 13:28:03.467 xmltv: /usr/bin/tv_grab_zap2epg10: grab returned no data

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Wes Beard<mailto:wbeard52@hotmail.com>
Sent: Tuesday, October 27, 2020 1:21 PM
To: edit4ever/script.module.zap2epg<mailto:reply@reply.github.com>
Subject: RE: [edit4ever/script.module.zap2epg] Scrap fails with message "xmltv: /usr/bin/tv_grab_zap2epg: htsmsg_xml_deserialize error Unknown syntatic element:" (#24)

No.  Unfortunately.  I was looking for a line number.  After that line, it simply stated it grabbed no data.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
No worries – I think it’s an issue with the non-ascii characters and the python update.

The code in zap2epg.py is old and not up to current python standards.  It really needs to be rewritten.

However – I’m going to try a workaround for now – if I get it to run I’ll send you the file to test.


Jay M

**Comment by edit4ever** [comment]
OK – try replacing your zap2epg.py file with the one I the attached zip.

You’ll need to rename it to zap2epg.py

Jay M

**Comment by crwolff** [comment]
zap2it appears to require gzip encoding now

In place of:
                    saveContent = urllib2.urlopen(url).read()
Try:
                    req = urllib2.Request(url)
                    req.add_header( 'Accept-Encoding', 'gzip' )
                    resp = urllib2.urlopen(req)
                    if resp.info().get('Content-Encoding') == 'gzip':
                        buf = StringIO(resp.read())
                        saveContent = gzip.GzipFile(fileobj=buf).read()
                    else:
                        saveContent = resp.read()

**Comment by edit4ever** [comment]
I actually think the issue is Python 3 - the code of zap2epg.py is Python 2 --- I just sent a test python 3 version to @wbeard52 However - he needs to test to see if the os/kodi version he is running will read the generated xmltv file.

**Comment by wbeard52** [comment]
I didn’t get the zip fil :-<


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
Here's a link to download the file:
https://www.dropbox.com/s/hnc32hwb7m7oqvm/zap2epg-3.py?dl=0

You will still need to rename it once you copy to your addon folder.

**Comment by wbeard52** [comment]
Thank you!

2020-10-27 13:57:36.062 xmltv: /usr/bin/tv_grab_zap2epg: grab /usr/bin/tv_grab_zap2epg
2020-10-27 13:57:36.068 spawn: Executing "/usr/bin/tv_grab_zap2epg"
2020-10-27 13:57:36.358 spawn: Traceback (most recent call last):
2020-10-27 13:57:36.358 spawn:   File "/home/osmc/.kodi/addons/script.module.zap2epg/zap2epg.py", line 17, in
2020-10-27 13:57:36.359 spawn:     import urllib.request, urllib.error, urllib.parse
2020-10-27 13:57:36.360 spawn: ImportError: No module named request
2020-10-27 13:57:36.414 xmltv: /usr/bin/tv_grab_zap2epg: htsmsg_xml_deserialize error Unknown syntatic element:
2020-10-27 13:57:36.414 xmltv: /usr/bin/tv_grab_zap2epg: grab returned no data

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wbeard52** [comment]
The new script errored out at line 17.   See TVH log below.  There was no logfile generated.

2020-10-27 13:57:36.062 xmltv: /usr/bin/tv_grab_zap2epg: grab /usr/bin/tv_grab_zap2epg
2020-10-27 13:57:36.068 spawn: Executing "/usr/bin/tv_grab_zap2epg"
2020-10-27 13:57:36.358 spawn: Traceback (most recent call last):
2020-10-27 13:57:36.358 spawn:   File "/home/osmc/.kodi/addons/script.module.zap2epg/zap2epg.py", line 17, in
2020-10-27 13:57:36.359 spawn:     import urllib.request, urllib.error, urllib.parse
2020-10-27 13:57:36.360 spawn: ImportError: No module named request
2020-10-27 13:57:36.414 xmltv: /usr/bin/tv_grab_zap2epg: htsmsg_xml_deserialize error Unknown syntatic element:
2020-10-27 13:57:36.414 xmltv: /usr/bin/tv_grab_zap2epg: grab returned no data

**Comment by edit4ever** [comment]
OK - that makes sense as the addon is set to use python 2 - I'll have to either send you a new full updated addon, or give you a modified python 2 version to test.

**Comment by wbeard52** [comment]
I have python2 and python3 installed if that helps.



  *   Python 2 – 2.7.13
  *   Python 3 – 3.7.3

**Comment by edit4ever** [comment]
OK - try installing this version (should install as an addon update):
https://1drv.ms/u/s!AhL4aRs7Xd05ivlTTDLm8YeQKeq58Q?e=sFqhk3

**Comment by wbeard52** [comment]
I do appreciate your help.  I get an error when trying to install the addon.  I am leaving and won’t be back till much later tonight.
From the kodi.log

2020-10-27 14:31:19.779 T:27536   ERROR: CAddonInstallJob[script.module.zap2epg]: The dependency on xbmc.python version 3.0.0 could not be satisfied.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
OK – I’ll keep looking into this.  Thanks.


Jay Maloney

**Comment by edit4ever** [comment]
If you get a chance - you can try this version:
https://1drv.ms/u/s!AhL4aRs7Xd05ivlZaLGAhGUyACxaIg?e=fcSEaf

That should just include a change to the encoding of the text - which may help.

**Comment by wbeard52** [comment]
Ugh.  No joy!.  Same error as the first one.


2020-10-27 22:49:32.000 xmltv: /usr/bin/tv_grab_zap2epg: grab /usr/bin/tv_grab_zap2epg

2020-10-27 22:49:32.005 spawn: Executing "/usr/bin/tv_grab_zap2epg"

2020-10-27 22:50:05.981 xmltv: /usr/bin/tv_grab_zap2epg: htsmsg_xml_deserialize error Unknown syntatic element:

2020-10-27 22:50:05.981 xmltv: /usr/bin/tv_grab_zap2epg: grab returned no data


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
bummer - thanks for the update.

I have a little more time later this week - I'll download and test OSMC Buster and see what is really going on.

**Comment by wbeard52** [comment]
Wow.  Thank you for your helkp!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edit4ever** [comment]
After getting OSMC installed and reviewed - turns out the issue is with the tvheadend release they are using.  It is not reading the doctype line correctly in the xmltv.xml file.

I released a workaround for now - which you can try here:
https://github.com/edit4ever/script.module.zap2epg/releases/tag/v1.3.1

Let me know if it works!

**Comment by wbeard52** [comment]
Thank you sir!  That fixed the issue.  I appreciate all the help.
