### ISSUE TITLE
zap2epg does not work w/ kodi 19

### ISSUE THREAD

**Issue by zeke56** [edit4ever/script.module.zap2epg#25]
It looks like zap2epg requires python 2.7 and my understanding is that python version is not supported in kodi 19. I love this addon and would very much like to keep using it!

**Comment by edit4ever** [comment]
Can you try this version and see if it works for you?
https://1drv.ms/u/s!AhL4aRs7Xd05ivlTTDLm8YeQKeq58Q?e=98nZ2Z

I haven't had a lot of time to go back and look at this project - but this simple python 3 coonversion may work.

**Comment by zeke56** [comment]
Hi, thanks very much for the link. Unfortunately both firefox and Chrome are giving me an error that the secure connection can't be made.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by edit4ever** [comment]
Here's a dropbox version:
https://www.dropbox.com/s/omf8qtf1pv9qs2d/script.module.zap2epg-3.zip?dl=0

**Comment by zeke56** [comment]
Great, thanks again, I'll try it out asap.

**Comment by zeke56** [comment]
It looks like the modified addon is working normally in the LibreELEC nightly build from 11/15 (sorry, don't know specific version of Kodi). Certainly it installed. I checked the log file and it seems to have downloaded data ok this morning. 
thanks

**Comment by edit4ever** [comment]
Thanks for the update - I'll close this issue.  You can report another if you have trouble and I'll go ahead and release this version.
