### ISSUE TITLE
Running with old files in ./cache throws exception

### ISSUE THREAD

**Issue by msorice** [edit4ever/script.module.zap2epg#27]
Typical log:
2020/12/20 18:33:05 Kodi settings version is: 2
2020/12/20 18:33:05 Running zap2epg-0.7.4 for zipcode: ***** and lineup: Local Over the Air Broadcast
2020/12/20 18:33:05 No channel list found - adding all stations!
2020/12/20 18:33:05 Checking for old cache files...
2020/12/20 18:33:05 Exception: main
Traceback (most recent call last):
  File "./zap2epg.py", line 755, in mainRun
    deleteOldCache(gridtimeStart)
  File "./zap2epg.py", line 147, in deleteOldCache
    logging.exception('Exception: deleteOldCache - %s', e.strerror)
AttributeError: 'exceptions.NameError' object has no attribute 'strerror'

**Comment by edit4ever** [comment]
Thanks for the heads up-

It looks like you're running a very old version of zap2epg.  You might want to try updating.  Also note - there is a new version for Python 3 - depending on what system you are running.

**Comment by msorice** [comment]
Thanks for the useful and quick reply! I'm running Ubuntu 20.04 x86_64.

I cloned from Git (git clone https://github.com/edit4ever/script.module.zap2epg.git) -- the zap2epg.py in there wouldn't go with python3. How do I get newer versions?

**Comment by edit4ever** [comment]
download the 2.0 release here:
https://github.com/edit4ever/script.module.zap2epg/releases/tag/v2.0.0

**Comment by msorice** [comment]
Excellent. New version installed. Same error still occurs; typical log:
2020/12/20 20:35:09 Kodi settings version is: 2
2020/12/20 20:35:09 Running zap2epg-0.7.4 for zipcode: ***** and lineup: Local Over the Air Broadcast
2020/12/20 20:35:09 No channel list found - adding all stations!
2020/12/20 20:35:09 Checking for old cache files...
2020/12/20 20:35:09 Exception: main
Traceback (most recent call last):
  File "./zap2epg.py", line 139, in deleteOldCache
    if (int(oldfile)) < (gridtimeStart + (int(redays) * 86400)):
NameError: free variable 'redays' referenced before assignment in enclosing scope

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zap2epg.py", line 754, in mainRun
    deleteOldCache(gridtimeStart)
  File "./zap2epg.py", line 146, in deleteOldCache
    logging.exception('Exception: deleteOldCache - %s', e.strerror)
AttributeError: 'NameError' object has no attribute 'strerror'

**Comment by msorice** [comment]
I've discovered this only occurs in the use case that the script is run from the same directory it's in. If run using, e.g., tv_grab_zap2epg, this error does not occur.
