### ISSUE TITLE
tv_grab_zap2epg does not show up in tvheadend EPG Grabber Modules

### ISSUE THREAD

**Issue by mathieugouin** [edit4ever/script.module.zap2epg#29]
Hello, first thanks for this wonderful addon!

I have used it in my current LibreELEC setup with a raspberry PI successfully.  I even forked it to make some minor fixes.

For various performance reasons, I've decided to slowly re-create a new sdcard image from an older LibreELEC version and start again from scratch.

When installing the addon, I'm able to perform the configuration, setup my linup, download the EPG.  The only issue I have is that tv_grab_zap2epg does not show up in tvheadend EPG Grabber Modules.  For this reason, I cannot link xmltv EPG source to my channels in tvheadend.

Do you know what is the mechanism for tvheadend to "discover" your script and make it available?  This portion totally confuses me.

Thanks in advance!

**Comment by edit4ever** [comment]
Tvheadend looks for tv_grab_zap2epg in the /usr/bin folder on linux installs and on raspberry pi it should look in /storage/.kodi/addons/script.module.zap2epg/bin/tv_grab_zap2epg

The file needs to be executable - so on some linux installs you need to manually reset the permissions for executable.
This shouldn't be an issue on an RPi LibreELEC install.  Sometimes you do need a reboot for tvheadend to rescan the epggabbers after the install.

What version of LE are you running?  And which version of zap2epg did you install?

**Comment by mathieugouin** [comment]
That's funny.  I did reboot a few times trying to fix this.  I confirm the script is there and executable.

For some strange reason, when I rebooted again yesterday, it worked...  

Sorry about that.  And thanks for your reply!
