### ISSUE TITLE
zap2epg not talking to TVHeadend

### ISSUE THREAD

**Issue by dschroed-7** [edit4ever/script.module.zap2epg#31]
So sorry to be a bother, again!  I had to downgrade my whole system because my graphics driver is too old to run more current versions of everything.  I am now running Linux Mint 18.3, Kodi 18.9, TVHeadend 4.4.21,and am trying to run zap2epg 1.3.1.

I installed zap2epg in Kodi, copied the tv_grab_zap2epg to /usr/bin and made it executable, then in Kodi set up my location and OTA information, as well as the Tvheadend username and password in zap2epg.  I selected the channels and can Run zap2epg and Update Guide Data.  However, when I go into Tvheadend through my browser, I don't have the option of "tv_grab_zap2epg is a simple grabber for USA-Canada" as an EPG Grabber Module. I have no zap2epg.log and the settings.xml have not been updated with my zip code, etc.

I had to install TVHeadend through snap, so it may all be that they can't talk to each other through snap.

Or, am I on an impossible mission to use an older zap2epg with a newer TVHeadend?  

Thanks so much for any assistance you can provide.

**Comment by edit4ever** [comment]
The version of tvheadend shouldn't make a difference.  It's more a matter of knowing where tvheadend is looking for the grabber file.  I assume you did restart the system so tvheadend would refresh the grabber list?

If you can find the other tvheadend grabbers - search your system for the `tv_grab_file` file - try putting tv_grab_zap2epg in the same location.  Then restart and see if it appears.

If you are able to successfully run the Update Guide Data function in the zap2epg addon in kodi - then there should be a zap2epg.log file in the kodi userdata zap2epg folder.  However - this won't be relevant to the issue with tvheadend.

Let me know how it goes.

**Comment by dschroed-7** [comment]
Thanks so much for your response.  Unfortunately, I am unable to copy the tv_grab_zap2epg file into the snap/tvheadend/... directory because it is a read-only file system.  I've been hitting a wall trying to make it work!  

Anyway, thanks so much for your help, again!  I guess I'm going to end up buying a new graphics card, or full computer, or maybe an NVIDIA Shield.  After a month of formatting and reformatting my computer, and trying so many different options, I just don't think I can make my old computer do what I need it to do anymore (as is).  It has certainly been a (very frustrating) learning experience, but I need to get a media server back!  Hopefully, I'll be able to proceed with zap2epg once I have an updated system.

**Comment by edit4ever** [comment]
Ever thought about getting a cheap Raspberry Pi and running that as your media server?  I actually use an RPi3 that's running the LibreELEC build of Kodi and it can run as a full media server as well as the tvheadend backend.  Then any device in your house can access that media.  :-)

**Comment by dschroed-7** [comment]
That was my first media server!  Unfortunately, I had to learn how to ssh into that (to which Linux terminal is very similar), and never got it all working well.  Then, it started working hot and I decided it was time for a change!  I was so much happier when I upgraded to Windows 7 with WMC, and could do everything I wanted without learning another language.  I really should have just stuck with that and switched to a different VPN (even with the unsupported OS), but had hoped that I was upgrading to an all around better system.  

I have ordered an NVIDIA Shield Pro, and hopefully that will suffice until I don't care what I watch anymore.  It is scheduled to arrive tomorrow, so I may be up and running again, soon.  If that doesn't do everything I want, I will be reconsidering the RPi!

Again, I really appreciate your assistance throughout this whole ordeal!

**Comment by edit4ever** [comment]
I assume you're going to then use Live Channels with a USB tuner for OTA TV?

**Comment by dschroed-7** [comment]
I am going to show my ignorance, once again...  I hope to use HDHomerun, TVHeadend, and zap2epg through Kodi on the NVIDIA Shield, because I hate commercials and, in most instances, prefer to record live TV.   Will I be able to do that?  It seemed like I could, with all of my research.  If not, I will probably end up getting HDHomerun's DVR service (though, I'd much prefer zap2epg).

**Comment by edit4ever** [comment]
The Nvidia Shield has Android Live Channels built into it.  If you install the Live Channels app – it should detect the HDHomerun on your network and setup live TV viewing – with a channel guide.  No zap2epg or tvheadend required.  😊

You can also try using the HDHomerun app on the Nvidia Shield and it should do the same thing.

**Comment by dschroed-7** [comment]
But, I don't think Android Live Channels offers a DVR option.  Though, there are so many available apps, that I may be missing one that will do just that.  Either way, hopefully (for your sake), you will be rid of me !-)

**Comment by edit4ever** [comment]
Live channels can record if you setup your extra storage as adoptable.  It’s not the best interface – but it does work.  I was using it on an old Channel Master Stream + for awhile.  I like the setup on my RPi3 for local – but in the end.  I went with the Fire TV Recast for ease of use by my wife! 😉

Good luck!

**Comment by dschroed-7** [comment]
Thanks for that information about Live Channels.  Glad to know I can record with it!  

Thanks, again for all of your help!
