### ISSUE TITLE
Unable to configure channel list and EPG data is 1 hour behind - libreelec rpi 4

### ISSUE THREAD

**Issue by minnixtx** [edit4ever/script.module.zap2epg#33]
Libreelec 9.95.2 10.0
Kodi 19.0
Raspberry Pi 4 4GB
zap2epg 2.02
tvheadend 4.2

When I go to configure channel list and hit ok zap2epg throws an error and says to see log.

When I run zap2epg it appears successful and guide data is populated, but it's all 1 hour behind. On the tvheadend web interface the EPG data is correct with the right times. I've attached my kodi and addon logs.

[libreelec_logs.zip](https://github.com/edit4ever/script.module.zap2epg/files/6446997/libreelec_logs.zip)

**Comment by edit4ever** [comment]
Unfortunately the menu system that zap2epg uses for running the addon is having some issues with Python 3 and will likely have to be reworked.

As for the timezone issue - I assume you have your timezone set correctly on Kodi?  I believe I've seen this before with daylight saving time causing issues for some listings.  I'll have to investigate.

**Comment by minnixtx** [comment]
Yes timezone is set to US/Chicago and I am in Dallas, both Central. When I used your addon previously with Kodi 18 and Libreelec on a rockpro64 I didn't have this issue, only since migrating to 19 and a RPi 4.

**Comment by edit4ever** [comment]
Thanks...I’ll do some investigating this week when I get a chance.

I also noticed in your logs that there is an issue/failure with parsing extra details - so you might want to turn that option off for now as it’s not adding anything to your guide.

**Comment by minnixtx** [comment]
Ok will do
