### ISSUE TITLE
Will this script run into any issues by using one account for zap2it for all script users?

### ISSUE THREAD

**Issue by kianrafiee** [edit4ever/script.module.zap2epg#4]
Just wondering since there is no zap2it login information in the script, I am guessing your using one single zap2it account to grab data for everyone using the script. Won't this potentially pose a problem where zap2it sees an overload of requests from this single account and disables/bans it? I just want to make sure this script is working for the foreseeable future for everyone :)

**Comment by edit4ever** [comment]
zap2it does not require a username/password to view guide listings. The zap2epg is anonymous, just like visiting the website without signing in.

**Comment by kianrafiee** [comment]
Oh I didnt know that. I guess that functionality was only for allowing favorites-only epg. Sweet. Great work on this! I'm not setup completely yet but the guide data was produced and accurate so I am happy so far.

**Comment by kianrafiee** [comment]
I really think you should make it more pronounced on the github main page and in the Wiki that this works awesome on Synology NAS's and other NAS's with Python. There are many many users like me that need this tool and probably don't know because googling is very scarce on the topic and returns the tvheadend forum page which is very convoluted. If I had some time right now I would help you with that.

**Comment by edit4ever** [comment]
Thanks for the feedback...most people who setup a NAS have a number of good options - so I wasn't really focused on that purpose.  Good to know it is working well in that setup.  Hopefully my wiki pages help with users who want to use it that way.  I'll add a link from the home page  to reference that.
