### ISSUE TITLE
Exception: xmltv error running zap2epg on TVheadend

### ISSUE THREAD

**Issue by SawKyrom** [edit4ever/script.module.zap2epg#40]
The script is unable to generate an xmltv file from the cacheDir.  I get the following error after data pull and parse:

```
2021/07/01 06:34:44 Parsing SH00003707.json
2021/07/01 06:34:44 Exception: xmltv
Traceback (most recent call last):
  File "<string>", line 432, in xmltv
  File "/usr/lib/python3.7/codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
IsADirectoryError: [Errno 21] Is a directory: '/usr/share/tvheadend/data/conf/epggrab/cache'
2021/07/01 06:34:44 zap2epg completed in 773.64 seconds. 
2021/07/01 06:34:44 Exception: main
Traceback (most recent call last):
  File "<string>", line 835, in mainRun
NameError: name 'stationCount' is not defined
```
The error states correctly that the /usr/share/tvheadend/data/conf/epggrab/cache path is a directory.   Also, is the Exception: xmltv log an error or report that no xmltv file exist?  

Any feedback would be much appreciated.  Thanks for your time and sharing your knowledge!

**Comment by edit4ever** [comment]
Which version of zap2epg and on what system are you running?

**Comment by SawKyrom** [comment]
This was a result of user error and not programming conflict.  I discovered that I had the` ConfDir="$BaseDir/conf"` improperly mapped and also had a conflicting path within the Config>ChannelEPG>EPG Grabber Modules>Parameters>Extra arguments setting of `--config-file FILENAME:`

Thanks for the reply!  Issue resolved.  Hope this helps someone else.
