### ISSUE TITLE
Zap2epg and OSMC/Kodi issues

### ISSUE THREAD

**Issue by BGI-YYZ** [edit4ever/script.module.zap2epg#43]
Hi, I'm still having issues with getting zap2epg working on my Vero4K box that is running OSMC and Kodi 19.

You may recall all the issues I was having and so I am trying again.  Here is what I have done.

1. I wiped the device and reinstalled OSMC again.
2. I installed TVHeadend (TVH) and got it to register the fact that I have an HDHomerun on my network for watching antenna TV.  I have somewhat of an EPG from whatever information is available from the TV signal, but it's pretty inadequate and that's why I'd like to get zap2epg running again.
3. I installed the custom zap2epg you had previously made for me (with the Python 3 references)
4. I double checked and `/home/osmc/.kodi/addons/script.module.zap2epg/bin/tv_grab_zap2epg`, line 28 definitely reads `python3 $ADDON_DIR/zap2epg.py`
5. I then modified the octal for `/home/osmc/.kodi/addons/script.module.zap2epg/bin/tv_grab_zap2epg` to 0755
6. As you suggested, I also copied  tv_grab_zap2epg to `/usr/bin` - where it is also octal 0755
7. It had been suggested elsewhere that I edit the zap2epg.py file and add `#!/usr/bin/env python3` at the top.  I added it to line 16 above `import urllib`

Incidentally, I can go into the settings section of zap2epg within Kodi and change things like the TVH IP address, etc, without issue, but when I choose to run zap2epg, it says that there has been an error and to check the log.

You had previously indicated that xmbcswift2 may (or is) the issue in my case.  I know that xmbcswift2 is definitely installed.  Whether there is something broken in xmbcswift2, I don't know.  Maybe the log can point someone who knows more than me in the right direction.

The log is here:  [https://paste.osmc.tv/kizebezapu](https://paste.osmc.tv/kizebezapu)

Thanks.

**Comment by edit4ever** [comment]
The issue you are having is tied to xbmcswiftpython module - as I mentioned here: https://github.com/edit4ever/script.module.zap2epg/issues/42#issuecomment-907897162.

I'm guessing OSMC has not ported over the Python 3 version of this - but maybe someone on that forum can help get that module installed - which would then allow zap2epg to run.

Your other option is to not run the addon configuration for zap2epg and manually setup your settings.xml file -- tvheadend only needs this file to run the grabber. xbmcswift is used to build the menu for the zap2epg addon when you run it to setup your settings - like lineup and channels.

**Comment by BGI-YYZ** [comment]
Thank you again.  I suspected that the problem still lay with xbmcswift2, but I wanted to confirm with you as I had completely wiped the device and reinstalled OSMC.   Apparently that didn't make a difference.

I tried manually editing settings.xml in the `/home/osmc/.kodi/addons/script.module.zap2epg/` folder, but it doesn't seem to have worked.  Should I move or copy settings.xml to somewhere else?

**Comment by edit4ever** [comment]
When you say it doesn't work - do you mean zap2epg won't run inside of tvheadend?  Or do you mean you can't open the addon in kodi?

FYI - you won't be able to run the addon in Kodi without xbmcswift installed.  But the zap2epg grabber should function in tvheadend.

**Comment by BGI-YYZ** [comment]
Well, what I did was install zap2epg within Kodi.  The installation appears to go okay.  In Kodi, I can choose "Configure" and am allowed to input my postal code, how many days I want to download, etc.  I cannot, however, choose "Open".  Doing so gives me the error we see in the log.  I really cannot do anything else with it in Kodi.

I go to my computer and remotely log into my OSMC box and did a search for settings.xml and it found loads.  I guess it is a common file used for all sorts of things.  Anyway, ignoring anything that doesn't mention zap2epg, I copies in the following folders.
`./proc/self/task/3240/cwd/.kodi/userdata/addon_data/script.module.zap2epg` (this file show the correct postal code)
`./proc/self/task/3240/cwd/.kodi/addons/script.module.zap2epg` (this file shows the default info with the 92010 zip code)
`./proc/self/task/3240/cwd/.kodi/addons/script.module.zap2epg/resources` (this file shows a big list of settings, mostly with `catagory label` in them)

I did not manually copy any of these files or folders to these various locations, it must have been done when it was installed in Kodi.

I did manually edit the settings.xml that showed the 92010 zip code to read my postal code, etc.

There doesn't seem to be any settings.xml in a folder than mentions TVH. 

In TVH (in a computer browser), if I go to Configuration -> Channel/EPG -> EPG Grabber Modules, there is no listing for zap2epg.

In the past, I could go in Kodi and choose "Open" in zap2epg and it would download everything and say that it successfully downloaded x amount of days worth of EPG info.  Since I can no longer open zap2epg, I don't know how to run it or make activate.

Lastly, I don't know if this is useful, but here is a list of every settings.xml file found.

/proc/self/task/3240/cwd/.kodi/userdata/addon_data/script.xbmc.unpausejumpback/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/script.module.osmcsetting.logging/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/service.subsmangler/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/metadata.tvshows.themoviedb.org.python/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/skin.osmc/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/service.stinger.notification/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/skin.estuary/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/pvr.hts/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/metadata.themoviedb.org.python/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/weather.gismeteo/settings.xml
_**/proc/self/task/3240/cwd/.kodi/userdata/addon_data/script.module.zap2epg/settings.xml**_
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/script.module.osmcsetting.apfstore/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/service.subtitles.opensubtitles/settings.xml
/proc/self/task/3240/cwd/.kodi/userdata/addon_data/service.autosubs/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/script.xbmc.unpausejumpback/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/service.upnext/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.tvshows.themoviedb.org/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/service.subsmangler/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/plugin.video.cbc/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.tvshows.themoviedb.org.python/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/script.module.inputstreamhelper/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/service.subtitles.rvm.addic7ed/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.album.universal/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.artists.universal/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/service.stinger.notification/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.tvdb.com/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/script.logviewer/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.universal/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.themoviedb.org.python/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/weather.gismeteo/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/metadata.thexem.de/resources/settings.xml
_**/proc/self/task/3240/cwd/.kodi/addons/script.module.zap2epg/settings.xml**_
_**/proc/self/task/3240/cwd/.kodi/addons/script.module.zap2epg/resources/settings.xml**_
/proc/self/task/3240/cwd/.kodi/addons/service.subtitles.opensubtitles/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/service.autosubs/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/weather.multi/resources/settings.xml
/proc/self/task/3240/cwd/.kodi/addons/script.kodi.loguploader/resources/settings.xml
/usr/share/kodi/addons/pvr.njoy/resources/settings.xml
/usr/share/kodi/addons/audioencoder.kodi.builtin.wma/resources/settings.xml
/usr/share/kodi/addons/visualization.waveform/resources/settings.xml
/usr/share/kodi/addons/pvr.vbox/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.2sf/resources/settings.xml
/usr/share/kodi/addons/pvr.mythtv/resources/settings.xml
/usr/share/kodi/addons/screensaver.pingpong/resources/settings.xml
/usr/share/kodi/addons/screensaver.greynetic/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.lattice/resources/settings.xml
/usr/share/kodi/addons/script.module.osmcsetting.logging/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.vgmstream/resources/settings.xml
/usr/share/kodi/addons/screensaver.xbmc.builtin.dim/resources/settings.xml
/usr/share/kodi/addons/script.module.osmcsetting.services/resources/settings.xml
/usr/share/kodi/addons/peripheral.joystick/resources/settings.xml
/usr/share/kodi/addons/metadata.tvshows.themoviedb.org/resources/settings.xml
/usr/share/kodi/addons/pvr.dvblink/resources/settings.xml
/usr/share/kodi/addons/metadata.generic.artists/resources/settings.xml
/usr/share/kodi/addons/vfs.rar/resources/settings.xml
/usr/share/kodi/addons/pvr.hdhomerun/resources/settings.xml
/usr/share/kodi/addons/visualization.pictureit/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.hufosmoke/resources/settings.xml
/usr/share/kodi/addons/audioencoder.vorbis/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.cyclone/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.drempels/resources/settings.xml
/usr/share/kodi/addons/script.module.osmcsetting.remotes/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.sacd/resources/settings.xml
/usr/share/kodi/addons/service.osmc.settings/resources/settings.xml
/usr/share/kodi/addons/script.module.osmccommon/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.flocks/resources/settings.xml
/usr/share/kodi/addons/pvr.teleboy/resources/settings.xml
/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.organya/resources/settings.xml
/usr/share/kodi/addons/pvr.mediaportal.tvserver/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.skyrocket/resources/settings.xml
/usr/share/kodi/addons/pvr.zattoo/resources/settings.xml
/usr/share/kodi/addons/metadata.themoviedb.org/resources/settings.xml
/usr/share/kodi/addons/game.libretro/resources/settings.xml
/usr/share/kodi/addons/skin.osmc/xml/Settings.xml
/usr/share/kodi/addons/screensaver.rsxs.spirographx/resources/settings.xml
/usr/share/kodi/addons/skin.estouchy/xml/Settings.xml
/usr/share/kodi/addons/visualization.fishbmc/resources/settings.xml
/usr/share/kodi/addons/skin.osmc.scope/xml/Settings.xml
/usr/share/kodi/addons/pvr.argustv/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.colorfire/resources/settings.xml
/usr/share/kodi/addons/pvr.sledovanitv.cz/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.timidity/resources/settings.xml
/usr/share/kodi/addons/screensaver.shadertoy/resources/settings.xml
/usr/share/kodi/addons/visualization.matrix/resources/settings.xml
/usr/share/kodi/addons/visualization.shadertoy/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.flux/resources/settings.xml
/usr/share/kodi/addons/screensaver.matrixtrails/resources/settings.xml
/usr/share/kodi/addons/screensaver.biogenesis/resources/settings.xml
/usr/share/kodi/addons/metadata.album.universal/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.ssf/resources/settings.xml
/usr/share/kodi/addons/screensaver.asterwave/resources/settings.xml
/usr/share/kodi/addons/metadata.artists.universal/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.feedback/resources/settings.xml
/usr/share/kodi/addons/skin.estuary/xml/Settings.xml
/usr/share/kodi/addons/visualization.goom/resources/settings.xml
/usr/share/kodi/addons/script.module.osmcsetting.updates/resources/settings.xml
/usr/share/kodi/addons/pvr.stalker/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.busyspheres/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.fieldlines/resources/settings.xml
/usr/share/kodi/addons/inputstream.ffmpegdirect/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.fluidsynth/resources/settings.xml
/usr/share/kodi/addons/pvr.freebox/resources/settings.xml
/usr/share/kodi/addons/pvr.iptvsimple/resources/settings.xml
/usr/share/kodi/addons/inputstream.adaptive/resources/settings.xml
/usr/share/kodi/addons/pvr.hts/resources/settings.xml
/usr/share/kodi/addons/audioencoder.kodi.builtin.aac/resources/settings.xml
/usr/share/kodi/addons/pvr.dvbviewer/resources/settings.xml
/usr/share/kodi/addons/pvr.filmon/resources/settings.xml
/usr/share/kodi/addons/metadata.themoviedb.org.python/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.solarwinds/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.hufotunnel/resources/settings.xml
/usr/share/kodi/addons/pvr.waipu/resources/settings.xml
/usr/share/kodi/addons/pvr.wmc/resources/settings.xml
/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/settings.xml
/usr/share/kodi/addons/audiodecoder.ncsf/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.helios/resources/settings.xml
/usr/share/kodi/addons/pvr.nextpvr/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.sundancer2/resources/settings.xml
/usr/share/kodi/addons/pvr.vuplus/resources/settings.xml
/usr/share/kodi/addons/visualization.spectrum/resources/settings.xml
/usr/share/kodi/addons/script.module.osmcsetting.apfstore/resources/settings.xml
/usr/share/kodi/addons/screensaver.rsxs.lorenz/resources/settings.xml
/usr/share/kodi/addons/pvr.vdr.vnsi/resources/settings.xml
/usr/share/kodi/addons/audioencoder.lame/resources/settings.xml
/usr/share/kodi/addons/metadata.generic.albums/resources/settings.xml
/usr/share/kodi/addons/audioencoder.flac/resources/settings.xml
/usr/share/kodi/addons/pvr.octonet/resources/settings.xml
/usr/share/kodi/addons/pvr.pctv/resources/settings.xml
/usr/share/kodi/system/settings/settings.xml

**Comment by edit4ever** [comment]
Try installing xbmcswift and see if that helps:

https://github.com/XBMC-Addons/script.module.xbmcswift2/releases/tag/19.0.5

**Comment by BGI-YYZ** [comment]
That version of xbmcswift2 was already installed from the official Kodi repository.  Nonetheless, I downloaded and installed it from the link you provided, but it didn't help.  Same error when trying to open zap2epg within Kodi.

I'm sure this issue has been a major pain for you.  I'm happy to manually set things up if that is a viable work around.  I went through the instructions on how to edit the settings.xml, but there must be additional steps that I don't know how to do to activate it or something.

**Comment by crwolff** [comment]
I don't have an OSMC system, but the file should be in: 
/home/osmc/.kodi/userdata/addon_data/script.module.zap2epg/settings.xml

The files in /proc/... are temporary system files which will move around (and get erased) after a reboot. If the file isn't in that location, copy the best version from the /proc tree and edit from there.

**Comment by BGI-YYZ** [comment]
@crwolff Thanks for clearing that up.  I didn't know about the /proc/ folders being temporary.  Unfortunately, /home/osmc/.kodi/userdata/addon_data/script.module.zap2epg/settings.xml is edited to read with my proper postal code and it still doesn't seem to be working.

**Comment by edit4ever** [comment]
So for your case - let's try a step by step from the beginning.

- Uninstall zap2epg
- Delete any manually copied zap2epg files including the grabber file from usr/bin
- Download the current release of zap2epg: https://github.com/edit4ever/script.module.zap2epg/releases/download/v2.0.3/script.module.zap2epg-2.0.3.zip
- install that addon
- restart the system

Once that is done - do you see the zap2epg grabber in the tvheadend?

**Comment by BGI-YYZ** [comment]
I have uninstalled and deleted anything zap2epg related from usr/bin.  Before installing the current release of zap2epg, should I use 2.0.3 or 2.0.4-Ph3 that you had previously given me?

**Comment by edit4ever** [comment]
Let's go back to the 2.0.3 version.  And I assume you're running the August 1st release of OSMC?

**Comment by BGI-YYZ** [comment]
Yes, I'm running August 1 release of OSMC.

Install appeared to have run successfully.  It let me go in and input my postal code and choose signal type (local over the air) and then run it.  It finished with saying it had downloaded X amount of shows, etc.

The TVHeadend section of zap2epg shows the correct IP, username & password.  I have rebooted the OSMC box several times and there is no zap2epg when viewing TVH on my computer, Configuration -> Channel / EPG -> EPG Grabber Modules does not list zap2epg  at all.

**Comment by edit4ever** [comment]
OK - does the zap2epg grabber show up in the tvheadend webUI?

**Comment by edit4ever** [comment]
If so - gave you enabled it?  Checked the enabled box and hit save?

**Comment by edit4ever** [comment]
Your system may not have set the tv_grab_zap2epg file as executable.

Make sure the file at /home/osmc/.kodi/addons/script.module.zap2epg/bin/tv_grab_zap2epg is set to executable.

**Comment by BGI-YYZ** [comment]
/home/osmc/.kodi/addons/script.module.zap2epg/bin/tv_grab_zap2epg properties says the group is osmc [1000] and owner is [1000].  The octal is set to 0755 (rwxr-xr-x)

**Comment by edit4ever** [comment]
If you still can't see the tv_grab_zap2epg grabber in Configuration -> Channel / EPG -> EPG Grabber Modules then the hts user needs to be added to the tv_grab_zap2epg file.

Looks like OSMC is stopping tvheadend from seeing/running it.  tvheadend accesses files using an hts user in the video group.

**Comment by edit4ever** [comment]
You can also see about adding the file to the video group

**Comment by edit4ever** [comment]
I wonder if you could also try adding the osmc user to tvheadend - but I don't think that would be needed.

**Comment by edit4ever** [comment]
Also - if necessary - you could copy the tv_grab_zap2epg to /usr/bin and that should solve the issue of it not showing up in tvheadend.

**Comment by BGI-YYZ** [comment]
> If you still can't see the tv_grab_zap2epg grabber in Configuration -> Channel / EPG -> EPG Grabber Modules then the hts user needs to be added to the tv_grab_zap2epg file.
> 
> Looks like OSMC is stopping tvheadend from seeing/running it. tvheadend accesses files using an hts user in the video group.

How do I do this?  I am looking at tv_grab_zap2epg file and I can't see any mention of users.

**Comment by edit4ever** [comment]
don't worry about - make your life simple and just copy the grabber to /usr/bin reboot and see if it shows up in tvheadend

**Comment by BGI-YYZ** [comment]
Okay, I copied tv_grab_zap2epg to /usr/bin and then changed the octal to 0755 and rebooted.

In the webUI of TVH, there are now 2 versions of tv_grab_zap2epg showing up.  Highlighting them shows the first one having a path of /bin/tv_grab_zap2epg and the second one having a path of /usr/bin/tv_grab_zap2epg.

I've left them disabled for now.

**Comment by edit4ever** [comment]
Your system is likely copying from usr/bin to /bin during startup - but it doesn't matter.

Go ahead and enable the one in /usr/bin

**Comment by BGI-YYZ** [comment]
done.  I've also disabled the ATSC grabber that I was previously using

**Comment by edit4ever** [comment]
now try to run the grabber (from the tvheadend UI) and monitor the status window of tvheadend

**Comment by BGI-YYZ** [comment]
I ran it and in the log it shows the following 4 times 2021-09-22 18:57:42.292 spawn: Executing "/usr/bin/tv_grab_zap2epg"
2021-09-22 18:57:42.563 spawn: Traceback (most recent call last):
2021-09-22 18:57:42.563 spawn:   File "/home/osmc/.kodi/addons/script.module.zap2epg/zap2epg.py", line 17, in 
2021-09-22 18:57:42.563 spawn:     import urllib.request, urllib.error, urllib.parse
2021-09-22 18:57:42.563 spawn: ImportError: No module named request
2021-09-22 18:57:42.653 xmltv: /usr/bin/tv_grab_zap2epg: grab took 0 seconds
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg: parse took 0 seconds
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg:  channels   tot=   23 new=    0 mod=    0
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg:  brands     tot=    0 new=    0 mod=    0
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg:  seasons    tot= 1924 new= 1924 mod= 1924
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg:  episodes   tot= 1935 new= 1441 mod= 1441
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg:  broadcasts tot= 1935 new=    0 mod=    0
2021-09-22 18:57:42.767 xmltv: /usr/bin/tv_grab_zap2epg: scheduling save epg timer

**Comment by edit4ever** [comment]
Awesome - now take a look at the EPG guide in tvheadend

**Comment by BGI-YYZ** [comment]
Well, the EPG is populated, but is it leftovers from the ATSC grabber?

**Comment by edit4ever** [comment]
no - it should have a lot more data than that.  It filled in from the sample run you did when you setup zap2epg addon.  You said you had run it then - so an xmltv.xml was created and that's what tvheadend just read.

**Comment by edit4ever** [comment]
now - I don't like the urllib error - so that needs to be addressed.

See if you can run the zap2epg addon and run it from its main menu.

**Comment by BGI-YYZ** [comment]
I think it did indeed work as the show descriptions are much more detailed than before.  It looks like it did indeed work.  Is that error on line 17 of zap2epg.py mean anything important?

**Comment by edit4ever** [comment]
Try editing zap2epg.py - which is in the /home/osmc/.kodi/addons/script.module.zap2epg/ directory

change line 17 to `import urllib`

Then try to run the grabber from inside the tvheadend webUI and see if you get the same error

**Comment by BGI-YYZ** [comment]
Okay, I went up to the TV and, using Kodi, chose "run zap2epg and update Guide data".  After several seconds, it said it was successful and had updated a whole bunch of shows.

Changed line 17 in zap2epg.py from `import urllib.request, urllib.error, urllib.parse` to `import urllib` and re-ran the grabber in TVH.  No error.

2021-09-22 19:10:36.166 xmltv: /usr/bin/tv_grab_zap2epg: grab /usr/bin/tv_grab_zap2epg
2021-09-22 19:10:36.170 spawn: Executing "/usr/bin/tv_grab_zap2epg"
2021-09-22 19:10:36.716 xmltv: /usr/bin/tv_grab_zap2epg: grab took 1 seconds
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg: parse took 0 seconds
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg:  channels   tot=   23 new=    0 mod=    0
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg:  brands     tot=    0 new=    0 mod=    0
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg:  seasons    tot= 2031 new= 2031 mod= 2031
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg:  episodes   tot= 2044 new= 1565 mod= 1565
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg:  broadcasts tot= 2044 new=  108 mod=  116
2021-09-22 19:10:36.910 xmltv: /usr/bin/tv_grab_zap2epg: scheduling save epg timer

**Comment by edit4ever** [comment]
You sir - are good to go!

And it looks like I need to update a few things in this addon.  Enjoy!

**Comment by BGI-YYZ** [comment]
Thank you so much for putting up with my questions.  I truly appreciate it!

**Comment by edit4ever** [comment]
No worries - a lot of people helped me out when I was getting started with this project.  I don't really keep it up anymore, but it was interesting to go back and try to troubleshoot.  Looks like a couple of tweaks and it should be good to go for awhile longer.

**Comment by edit4ever** [comment]
BTW - depending on what skin you are using...some of the data that is added to the show description - like season and episode - might be showing on your screen already, so you don't need it in the description.

You can adjust all of the items that are added to the description in the addon settings to clean that up and make it look like you want.
