### ISSUE TITLE
Malformed xml syntax due to bad Zap2IT data

### ISSUE THREAD

**Issue by Kensit** [edit4ever/script.module.zap2epg#44]
First off, I am not positive this is something you need to address but I will explain what is happening and you can decide if it should be.

Recently, Zap2IT pushed some bad data in a episode of a program in which the text description contained characters that made the xml bad syntactically. Specifically the following string was inserted as an episode title "wvrdr_error_100<oest-of-th3-gs.gid30n>". This string was inserted into the xml file and resulted in the EPG ignoring all xml following where the syntax problem appeared date-wise.

Now, clearly this was Zap2IT's fault and likely a one-off (it only occurred in a single episode of a TV series, DC's Legends of Tomorrow. However, the bigger issue is, should zap2epg make sure that all data written to the xmltv file is syntactically good?

**Comment by jbreen60030** [comment]
I tripped over this one last week when it blew out my guide in Plex. 
If you're using the current version, it appears that adding the stitle=true in the settings.xml should resolve the issue (as it makes safe titles).  see release 2.0.3  (https://github.com/edit4ever/script.module.zap2epg/releases)

I modified my copy to HTML escape the title and descriptions (basically what the new 2.0.3 functionality added), but it was an older version that I had also added other functionality. 
It did rectify the issue.

**Comment by Rippert** [comment]
Hi, I'm using an older, python 2, version of Zap2EPG and seeing the same problem. Is there an easy way to escape all text values written to the XML file? 

I see this in the code for the title escape `safeTitle = re.sub('[\\/*?:"<>|]', "_", showTitle)`

Hoping to avoid trying to find all instances of variables written to the XML file and adding this kind of line to them, if possible, and really hoping not to have to upgrade everything to Kodi 19 to get the python 3 version as that requires a full OS upgrade on my system.

Thanks

**Comment by jbreen60030** [comment]
Likewise, I followed up on Lorne's reply and added my own, which is geared
towards the Python 2 versions.
