### ISSUE TITLE
pre-v2.0.0 versions of EPG Grabber no longer work in latest Linuxserver.io docker

### ISSUE THREAD

**Issue by squirtbrnr** [edit4ever/script.module.zap2epg#49]
This is not your issue, instead mine for holding onto v1.3.1 of your EPG grabber for so long.  This is more of a warning for others with a similar setup as me.

Synology DSM 6.2.4-25556 Update 2
Docker from Package Center
Linuxserver.io TVHeadend docker image (v117 to current)
any version of EPG grabber not written in python3 (pre v2.0.0 I believe)

When Linuxserver.io rebased the image to Alpine 3.15, they removed python2 and installed python3.  See the release comparison on GitHub https://github.com/linuxserver/docker-tvheadend/compare/09a2c71a-ls116...c7b713ed-ls120  This breaks any version of Zap2Epg that uses python2.  I am getting errors in my logs and EPG is not updating:
```
[  ERROR] epg: Unable to compile PCRE2 '[': missing terminating ] for character class
[  ERROR] epg: Unable to compile PCRE2 '\': \ at end of pattern
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg: grab /usr/bin/tv_grab_zap2epg
[   INFO] spawn: Executing "/usr/bin/tv_grab_zap2epg"
[  ERROR] spawn: /usr/bin/tv_grab_zap2epg: line 28: python: command not found
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg: grab took 1 seconds
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg: parse took 1 seconds
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg:  channels   tot=   48 new=    0 mod=    0
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg:  brands     tot=    0 new=    0 mod=    0
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg:  seasons    tot= 3678 new=  366 mod= 3312
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg:  episodes   tot= 2883 new=  408 mod= 2475
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg:  broadcasts tot= 3973 new=  458 mod=  239
[   INFO] xmltv: /usr/bin/tv_grab_zap2epg: scheduling save epg timer
[   INFO] epgdb: snapshot start
[   INFO] epgdb: queued to save (size 1875904)
[   INFO] epgdb:   broadcasts 3627
[   INFO] epgdb: save start
[   INFO] epgdb: stored (size 377947)
```

Looks like I either go back to v116 or I update to your latest zap2epg with python3 support.

**Comment by squirtbrnr** [comment]
The error about "`line 28: python: command not found`" is fixed in the by changing it to `python3` in the file `tv_grab_zap2epg`.  BUT this only applies if using v117 or newer of the Linuxserver.io docker image of TVHeadend which only has python3.

**Comment by wbeard52** [comment]
Updated code for python 3.6+
