### ISSUE TITLE
Problem with xbmc.translatePath in default.py file

### ISSUE THREAD

**Issue by electroman243** [edit4ever/script.module.zap2epg#57]
(Sorry I'm not a programmer)
The xbmc.translatePath return an error in the default.py file while I'm trying to run the addon for the first time:

![Capture](https://github.com/edit4ever/script.module.zap2epg/assets/49962069/0ef89f4e-a0a2-4cb9-861e-9f1612a6a30c)

It seems there is something that has changed in the addon xbmc: https://github.com/xbmc/xbmc/pull/19301

I've changed the line 34 in default.py file. Instead of using xbmc.translatePath, I putted xbmcvfs.translatePath and it's now working on my kodi setup (LibreElec 11.0.4)

**Comment by wbeard52** [comment]
It's been updated.  Thanks for the suggestion.
