### ISSUE TITLE
Is the code still maintained

### ISSUE THREAD

**Issue by wbeard52** [edit4ever/script.module.zap2epg#58]
Hi edit4ever,
Is this code still maintained?  I would like to update this for Kodi 20/21.  I have updated the script to further refine genre mapping and included the ability to determine the language of the show description.  I would like to know if you will let me manage and update this repo?

Thanks
wbeard52

**Comment by edit4ever** [comment]
I don't actually maintain this any longer.  Feel free to clone the repo and give it a new life!

**Comment by wbeard52** [comment]
I believe I cloned the repo.  I can fork it but I would prefer to work inside this repo.  Do you mind giving me write access?
________________________________
